[Config profile]: create base config profile
opentargets/genetics-app pull request #192
Opened 2022-02-01 14:41 UTC by carcruz

2022-02-01 14:59 UTC, mbdebian approved these changes

2022-02-02 10:40 UTC, mbdebian requested changes
Ideally, we should reduce the content of 'config.template' to its minimum, e.g. just the API URL, everything else is part of the customisation profiling subsystem.

2022-02-02 10:42 UTC, mbdebian requested changes
I think 'https://platform.opentargets.org' is the URL for Open Targets Platform, the one for genetics is probably 'https://genetics.opentargets.org'

2022-02-02 10:46 UTC, carcruz commented
@mbdebian comments addressed in https://github.com/opentargets/genetics-app/pull/192/commits/0faa0c1b4d2c9f0d8a1e12f97a6497497a96e6bb

2022-02-02 10:46 UTC, mbdebian approved these changes

2022-02-02 10:55 UTC, merged